Add pkg for TO-92 & TO-92-WIDE
LibrePCB-Libraries/LibrePCB_Base.lplib pull request #114
Opened 2023-09-06 20:39 UTC by ubruhin

##### SUMMARY

Probably one of the most used package of THT boards but still missing in the library :see_no_evil: 

The TO-92 package is used with legs bend in different ways. Either straight (non-bend), zigzag (TO-18 compatibility according Wikipedia) or bend to a larger pitch. Usually we would create only one package with different footprint variants for differently bend legs. However, this part is actually sold in different variants so bending does not necessarily needs to be done manually. At least non-bend and larger pitch are available, for zigzag I'm not sure.

Therefore, I think it makes sense to threat these as separate packages. For now, I created packages "TO-92" (straight legs) and "TO-92-WIDE". However, for private projects one might still bend the straight legs to get a larger pitch (for easier soldering) so I added footprint variants for all three bend styles to the "TO-92" package.

It's not perfect, but this way at least the default footprint will always correspond to the bend style of the actually sold part. If the user manually switches to a different footprint, it should be clear for him that this requires to bend the legs manually.

**TO-92-WIDE**:
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/25bb76ca-6fb0-4b1c-b92d-c6e9fb9ba75f)
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/3b611208-009c-4ee0-aa20-a914891c33f5)

**TO-92**:
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/eeeabd18-e372-4571-b07b-adf832367845)
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/3b2d3dd0-657b-44ef-bdbf-0dbdc058f42f)
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/78d9ed7c-ddf7-4d35-9788-c3e3a8f5d94d)
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/ca15b413-074f-4769-a42a-b55ae4934cdd)
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5374821/b19b2b5d-3deb-400f-adfa-92a7dad61631)

##### DATASHEETS / REFERENCES

- Wikipedia: https://en.wikipedia.org/wiki/TO-92
- JEDEC TO-092: https://web.archive.org/web/20170618095849/https://www.jedec.org/sites/default/files/docs/archive/to/to-092.pdf

##### OPEN QUESTIONS / UNRESOLVED ISSUES

See thoughts above.

##### CHECKLIST

- [x] I have read and followed the library conventions¹.
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] For modified elements, I bumped their version number².
- [ ] I already used the new library elements in a design and verified their correctness (optional).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

2023-09-07 20:26 UTC, dbrgn requested changes
(Looks good otherwise!)

2023-09-07 20:26 UTC, dbrgn commented on pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/package.lp
> + (description "Transistor outline package as specified by JEDEC TO-092 with straight (non-bend legs). For parts sold with bended legs for a larger pitch, use the \"TO-92-WIDE\" package instead!")
```suggestion
 (description "Transistor outline package as specified by JEDEC TO-092 with straight (non-bent legs). For parts sold with bent legs for a larger pitch, use the \"TO-92-WIDE\" package instead!")
```

2023-09-07 20:26 UTC, dbrgn commented on pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/package.lp
> + (description "Transistor outline package as specified by JEDEC TO-092, with legs bended for a larger pitch. Only use this package for parts which are sold with bend legs!")
```suggestion
 (description "Transistor outline package as specified by JEDEC TO-092, with legs bent for a larger pitch. Only use this package for parts which are sold with bent legs!")
```

2023-09-07 20:26 UTC, dbrgn commented on pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/package.lp
> + (keywords "to92,to-092")
According to Wikipedia, this package is also known as SOT54:

```suggestion
 (keywords "to92,to-092,sot54,sot-54")
```

2023-09-07 20:26 UTC, dbrgn commented on pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/package.lp
> + (keywords "to92,to-092")
According to Wikipedia, this package is also known as SOT54:

```suggestion
 (keywords "to92,to-092,sot54,sot-54")
```

2023-09-07 20:26 UTC, dbrgn commented on pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/package.lp
> +  (name "Zigzac (TO-18)")
```suggestion
  (name "Zigzag (TO-18)")
```

2023-09-08 12:35 UTC, ubruhin commented
Thanks for the fixes! :tada:

2023-09-08 12:35 UTC, merged